### ISSUE TITLE
fatal error in showip.c:30:28

### ISSUE THREAD

**Issue by furtive** [olignyf/raspberry-pi-showip#1]
When I try to make the package (using raspberry 4.14.98-v7+) I get

`showip.c:30:28: fatal error: lxpanel/plugin.h: No such file or directory`

When I check I've already got lxde-core and lxde installed.

**Comment by olignyf** [comment]
Fixed in v1.1
README.md also updated to show the new package dependencies

**Comment by olignyf** [comment]
The missing package was `lxpanel-dev`
